name: Semantic Version Tagging and Release

on:
  push:
    branches:
      - main

jobs:
  semver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git for tagging
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Magic Semver Action
        id: semver
        uses: mehdi-ra/semversion@v0.1.1
        with:
          addDate: 'true'

      - name: Create and push tag
        if: steps.semver.outputs.nextVersion != ''
        run: |
          git tag ${{ steps.semver.outputs.nextVersion }}
          git push origin ${{ steps.semver.outputs.nextVersion }}

      - name: Create GitHub release
        if: steps.semver.outputs.nextVersion != ''
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.semver.outputs.nextVersion }}
          release_name: "Release ${{ steps.semver.outputs.nextVersion }}"
          body: |
            ## Changes
            - New version created based on recent updates
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
